### ISSUE TITLE
Please add some examples of unit tests and CTest

### ISSUE THREAD

**Issue by solvingj** [ttroy50/cmake-examples#10]
The examples are extremely practical and helpful, so I'll be referring a lot of people to this repository. 

I think there are some conventions around unit test folders and files.  If you could show some examples of how that would look with any unit test framework I think it would be sensible addition.  Also, leveraging them with CTest would make sense if possible.

**Comment by ttroy50** [comment]
I have an example using boost test at https://github.com/ttroy50/cmake-examples/tree/master/05-unit-testing/boost.

I do hope to get around to adding other unit test libraries. Next up would probably be Google Test as I'm familiar with it and after that it would come down to how much time I have to investigate different ones.

**Comment by solvingj** [comment]
Somehow I didn't see that. i looked at this repo 50 times.
