### ISSUE TITLE
A-basic/subbinary/CMakeLists.txt doesn't build (my own project has similar error

### ISSUE THREAD

**Issue by rudock1** [ttroy50/cmake-examples#24]
Hi ttroy50, thanks for the tutorial, it has helped me very much.  Well done!  My personal project has a similar tree structure as your cmake-examples/02-sub-projects/A-basic/  with a couple of libraries and an app directory.  The libraries I build with cmake 3.10.2 & make work very well, like yours do.  However, my app binary does not.  I have worked and worked on this... which is how I found my way to your ttroy50/cmake-examples.

The reason I am writing is because my error turns out to be the same as the cmake & make errors I encounter in your cmake-examples/02-sub-projects/A-basic/subbinary/CMakeLists.txt.  Which is 'Target "subbinary" links to target "sub::lib1" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?'  etc etc

I was wondering if your /subbinary/CMakeLists.txt could be adjusted to clear these errors allowing it to generate a functional make on it.  If so, I suspect it will teach me how to fix my own equivalent build problem.

Thanks and best regards from Rio del Mar, California.  Billy

**Comment by ttroy50** [comment]
Are you building your libraries and binary from the same CMake project? If you are you may have left out the line about adding an alias target from your library. In my example I have

```
add_library(${PROJECT_NAME} src/sublib1.cpp)
add_library(sub::lib1 ALIAS ${PROJECT_NAME})
```

The first line generates the library, the second line generates an alias with the name `sub::lib1`. If that line is missing that the link to it from the binary target_link_libraries will fail
