### ISSUE TITLE
Shared library example

### ISSUE THREAD

**Issue by alandefreitas** [ttroy50/cmake-examples#25]
Hi,

In your example "cmake-examples/01-basic/D-shared-library/", what happens when we call main? Where does it look for the library? Can we define it somehow? When we package the software, is putting the library in the same folder as main enough?

Thank you for the examples,

**Comment by ttroy50** [comment]
By default when CMake builds a library it will set the RPATH in the binary with the location of the library. If you later do an install or generate an installer CMake will strip the build time RPATH from the binary

See https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling

You can see this being set when doing a VERBOSE build 

```
make VERBOSE=1
...
/usr/bin/c++     CMakeFiles/hello_binary.dir/src/main.cpp.o  -o hello_binary -Wl,-rpath,/path/to/workspace/cmake-examples/01-basic/D-shared-library/build libhello_library.so
...

And if you inspect your binary with objdump you can see it set

```
objdump -p hello_binary
objdump -p hello_binary 

hello_binary:     file format elf64-x86-64
...

Dynamic Section:
  NEEDED               libhello_library.so
  NEEDED               libc.so.6
  RUNPATH              /path/to/workspace/cmake-examples/01-basic/D-shared-library/build
```
