### ISSUE TITLE
Issue with shared library cmake example

### ISSUE THREAD

**Issue by WahabMohmadsharif** [ttroy50/cmake-examples#38]
Hey there, 
I was going through the examples to learn about cmake & i saw that for shared library examples if we are building the executable it will show following 
D:\Study\compiler\software\src\Hello.cpp(3): fatal error C1083: Cannot open include file: 'shared/Hello.h': No such fil
e or directory [D:\Study\compiler\software\build\hello_library.vcxproj]

**Comment by ttroy50** [comment]
Unfortunately I haven't tested on windows as I don't have access to a visual studio. Were you able to get this working in the end?
