### ISSUE TITLE
Setting C++ standard

### ISSUE THREAD

**Issue by militaryCoder** [ttroy50/cmake-examples#40]
Well, as far as I know, the "target_compile_features" feature is now deprecated.
[Where I found this issue](https://github.com/ttroy50/cmake-examples/blob/e36752873bb9480ec6ff71f40ac8ba880364a2e3/01-basic/L-cpp-standard/iii-compile-features/CMakeLists.txt#L13)

**Comment by ttroy50** [comment]
Do you have details on where you say that this was deprecated? It still seems to be valid in the latest docs from https://cmake.org/cmake/help/latest/command/target_compile_features.html
