### ISSUE TITLE
Create library with both target_include_directories and target_link_libraries

### ISSUE THREAD

**Issue by panovr** [ttroy50/cmake-examples#42]
Suppose I want to create a library which using Boost:

```
find_package(Boost 1.46.1 REQUIRED COMPONENTS filesystem system)
add_library(hello_library SHARED src/Hello.cpp)
target_include_directories(hello_library PUBLIC ${PROJECT_SOURCE_DIR}/include)
target_link_libraries(hello_library PRIVATE Boost::filesystem)
```

May I ask what is the difference between
`target_link_libraries(hello_library PRIVATE Boost::filesystem)`
and
`target_link_libraries(hello_library PUBLIC Boost::filesystem)`
?

**Comment by ttroy50** [comment]
The full CMake documentation for target_link_libraries is available from [here](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) and I have a brief explanation for how PUBLIC, PRIVATE, INTERFACE works in the [static library example](https://github.com/ttroy50/cmake-examples/tree/master/01-basic/C-static-library)

From a high level

- PUBLIC: `hello_library` and any library that links against it will also link to boost filesystem and have it's include directory in the path.
- PRIVATE: Only `hello_library` links against boost filesystem and has it's include directory in the path. Any library that uses `hello_library` doesn't know about boost filesystem.
- INTERFACE: `hello_library` doesn't link against boost filesystem and only libraries that use `hello_library` will link against it and have it in the include path.

The best way I have found to check this is to run an example and use verbose compiler output to see what flags are being passed to GCC or Clang.  

I'll see if I can add a clearer explanation in my examples.

**Comment by panovr** [comment]
As I understand, this will lead to necessary elements added to the target's  -I or -L flags.

Suppose `hello_library` has boost filesystem in its header files and cpp files, so any target linked to `hello_library` will have boost filesystem header file in its -I and boost filesystem library in -L flags.
This is `target_link_libraries(hello_library PUBLIC Boost::filesystem)` purpose.

In contrast, if `hello_library` only has boost filesystem in cpp files, not in its head files, so any target linked to `hello_library` doesn't need boost filesystem in its -I and -L flags.
 This is `target_link_libraries(hello_library PRIVATE Boost::filesystem)` purpose.

**Comment by ttroy50** [comment]
Yes that's correct and the intended use case for PUBLIC and PRIVATE.
