### ISSUE TITLE
[SUGGESTION] Multiple subfolder level

### ISSUE THREAD

**Issue by zpervan** [ttroy50/cmake-examples#48]
It would be useful if there would be an example that includes multiple directory levels.
Example:
```
├── CMakeLists.txt
└── subfolder
    └── CMakeLists.txt
    └── subfolder1
    │  └── CMakeLists.txt
    └── subfolder2
       └── CMakeLists.txt
```
I had a situation like that and manage to solve it. It would be nice to have a similar example (I did not manage to find one at least).

**Comment by ttroy50** [comment]
I have a simple of example of this with multiple libraries and a binary

https://github.com/ttroy50/cmake-examples/tree/master/02-sub-projects/A-basic

Does this cover your use case or is it the multiple hierarchy example that you want? 

The only difference between your request and my example is that your root `CMakeLists.txt` will use `add_subdirectory(subfolder)`, which will in turn use `add_subdirectory` on both `subfolder1` and `subfolder2`.

**Comment by zpervan** [comment]
Yes, it does! Thank you :)
