### ISSUE TITLE
Examples use 'old-style' definitions for include and link dependencies

### ISSUE THREAD

**Issue by socantre** [ttroy50/cmake-examples#5]
Current best practices in CMake are to define each target's include, link, and compile definitions on the target itself, using appropriate PRIVATE, PUBLIC, and INTERFACE annotations to define target usage requirements. This avoids issues caused by using 'global' configuration and enables automatic, transitive propagation of usage requirements. 

This does depend on updates made in recent versions of CMake. I believe 2.8 is the earliest to support this, with further improvements in 3.x versions.

**Comment by ttroy50** [comment]
Many of the examples were originally based on stuff I had working in 2.6 and 2.8 so they may be missing some newer best practices. I haven't worked with v3.x either so haven't looked at any of the newest features.

Do you have an example of (or link to) what you mean? Once I have that I can try to add an example showing the newer and older versions?

**Comment by ttroy50** [comment]
Fixed and updated master branch with new includes and linking
